name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [20]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and pnpm
        # 注意这里使用pnpm而不是npm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          # 更改为pnpm的缓存键
          cache: 'pnpm'
          # 安装pnpm版本
          pnpm-version: latest

      - name: pnpm install
        run: |
          pnpm install --frozen-lockfile

      - name: pnpm test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm run package
          pnpm run lint
          pnpm test
